sudo: false

language:
    - php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - hhvm
    - 7.4

dist: trusty

matrix:
    allow_failures:
        -   php: hhvm
    fast_finish: true
    include:
        -   php: 7.4
            env: SYMFONY_VERSION='5.3.*'

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --dev --no-interaction --prefer-dist
